### ISSUE TITLE
INVALID operation opcode.

### ISSUE THREAD

**Issue by rkart14** [wolflo/evm-opcodes#5]
Hi, 

Great costs...

`On execution of any invalid operation, whether the designated INVALID op or simply an undefined op, all remaining gas is consumed and the state is reverted to the point immediately prior to the beginning of the current execution context.`.

Could you explain what you mean by this ? if the revert happens, all remaining gas is NOT consumed, but it goes back to the caller's account

**Comment by wolflo** [comment]
This is true of `REVERT`, but not of `INVALID`. `INVALID` is unique in that it's not actually an opcode. That is, it doesn't exist in the list of operations that client implementations know how to handle (see geth's [opcodes](https://github.com/ethereum/go-ethereum/blob/master/core/vm/opcodes.go)).

`REVERT` is an EVM instruction with defined semantics (end execution, return remaining gas, and place `mem[ost:ost+len]` in returndata). But the EVM has several exceptional states that occur when the next operation cannot be executed. In all of these cases, the remaining gas is consumed and execution is ended.

There is a long list of things that can cause such an exception: overflowing or underflowing the stack, trying to jump to an invalid jump destination, trying to execute a state-changing opcode within a `STATICCALL`, running out of gas, trying to send `value > BALANCE` with a `CALL` or `CALLCODE`, using `CREATE2` to deploy to an account that already exists, exceeding the 1024 call depth limit, bad memory access*, or trying to execute an instruction that doesn't exist.

The last one means that any unassigned opcode does the same thing as the `INVALID` opcode. At some point compilers started using these unassigned opcodes to force execution to end, usually to indicate that something particularly bad or unexpected happened. But, unassigned opcodes can become assigned in the future. If you deploy a contract with the `0x0c` opcode, for example, it will cause an exception as of the Istanbul hardfork. In the future, though, it might be given some meaningful semantics that would change the semantics of your entire contract.

Because of this, everyone at some point ([EIP-141](https://github.com/ethereum/EIPs/issues/141)) came to a consensus that we would designate one of these unassigned opcodes and agree to never assign it in the future. So, `INVALID` is actually just an opcode that the EVM doesn't know how to execute and everyone has agreed that we will keep it that way.

As a more concrete example of `INVALID` vs `REVERT`, `REVERT` is what solidity uses if a `require()` condition is not met, while `INVALID` is used when an `assert()` condition is not met.

**Comment by rkart14** [comment]
Thanks for such a great answer. Really appreciated ! 

So, where does the remaining gas go ? the used gas would go to the miner, but the remaining gas ? does it just get burnt ?
